# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "vpa_butler"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/vpa_butler"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "test/crds/*",
]
SPDX-FileCopyrightText = "Copyright 2020 The Kubernetes Authors"
SPDX-License-Identifier = "Apache-2.0"
